# flake8: noqa
"""empty message

Revision ID: 2003c290b68
Revises: 
Create Date: 2015-07-13 11:27:21.904681

"""

# revision identifiers, used by Alembic.
revision = '2003c290b68'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hello',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Hello', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
    from sqlalchemy.sql import table, column
    from sqlalchemy import String, Integer

    hello_table = table('hello',
        column('id', Integer),
        column('Hello', String),
    )
    op.bulk_insert(hello_table, [{'id':1, 'Hello':'World'}])


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hello')
    ### end Alembic commands ###
