# flake8: noqa
"""empty message

Revision ID: 4661da48634
Revises: None
Create Date: 2015-07-14 07:40:40.270304

"""

# revision identifiers, used by Alembic.
revision = '4661da48634'
down_revision = None


from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=True),
    sa.Column('private_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key')
    ### end Alembic commands ###
